# istioctl kube-inject -f test.yaml | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: klog
  namespace: klog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klog
  template:
    metadata:
      labels:
        app: klog
    spec:
      imagePullSecrets:
      - name: registry-pull-secret
      containers:
      - command:
        - /opt/log-controller
        image: swr.cn-north-4.myhuaweicloud.com/cotte-internal/log:0.0.3-release
        imagePullPolicy: Always
        name: klog
        ports:
        - containerPort: 8080
          name: klog
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1200Mi
          requests:
            cpu: 50m
            memory: 1000Mi
#        volumeMounts:
#        - mountPath: /opt/web/ai/result
#          name: result
      serviceAccountName: default
#      volumes:
#      - name: result
#        persistentVolumeClaim:
#          claimName: efs-result

