apiVersion: v1
kind: Service
metadata:
  name: klog
spec:
  ports:
  - name: klog
    port: 8080
    protocol: TCP
    targetPort: klog
    nodePort: 38080
  type: NodePort
  selector:
    app: klog

