apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: klog
spec:
  gateways:
    - istio-system/gateway
  hosts:
#    - klog.lync2m.com
    - klog.prs.ciiplat.com
  http:
    - name: route-klog
      route:
        - destination:
            host: klog.klog.svc.cluster.local
            port:
              number: 8080
