apiVersion: apps/v1
kind: Deployment
metadata:
  name: klog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klog
  template:
    metadata:
      labels:
        app: klog
    spec:
      imagePullSecrets:
      - name: registry-pull-secret
      containers:
        - command:
            - /opt/log-controller
          image: registry.cn-hangzhou.aliyuncs.com/cotte-internal/log:0.0.2-ciiplat
          imagePullPolicy: Always
          name: klog
          ports:
          - containerPort: 8080
            name: klog
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1200Mi
            requests:
              cpu: 50m
              memory: 1000Mi
      serviceAccountName: default
