apiVersion: logcontroller.k8s.io/v1alpha1
kind: Log
metadata:
  name: klog
spec:
  prometheus:
    name: log
    #    protocol: http
    #    host: prometheus-k8s.monitoring
    #    port: "9090"
    #    period: 10
    protocol: http
    host: 172.16.77.155
    port: "39090"
    period: 10
  warning:
    sustained:
      cpu:
        step: 15
        range: 120
        warningValue: 90
        leftTime: 60
      memory:
        step: 15
        range: 120
        warningValue: 70
        leftTime: 60
    extremePointMedian:
      cpu:
        warningValue: 80
      memory:
        warningValue: 80

