apiVersion: logcontroller.k8s.io/v1alpha1
kind: Log
metadata:
  name: klog
spec:
  prometheus:
    name: log
    protocol: http
    host: prometheus-k8s.monitoring
    port: "9090"
    period: 10
#    protocol: http
#    host: 172.16.77.155
#    port: "39090"
#    period: 10
  warning:
    sustained:
      cpu:
        step: 15
        range: 150
        warningValue: 30
        leftTime: 120
      memory:
        step: 15klo
        range: 150
        warningValue: 70
        leftTime: 120
      disk:
        range: 120
        leftTime: 600
    extremePointMedian:
      cpu:
        warningValue: 80
      memory:
        warningValue: 80

