apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: klog
spec:
  gateways:
    - istio-system/gateway
  hosts:
    - klog.ciiplat.com
  http:
    - name: route-klog
      route:
        - destination:
            host: klog.monitoring.svc.cluster.local
            port:
              number: 8080
