apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  annotations:
    description: "{{.Describe}}"
    gitUrl: "{{.GitUrl}}"
    gatewayUrl: "{{.GatewayRealmName}}/{{.Name}}"
    innerUrl: "http://{{.Name}}.{{.Namespace}}:{{.Port}}"
spec:
  selector:
    matchLabels:
      app: {{.Name}}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: {{.Name}}
    spec:
      terminationGracePeriodSeconds: 5
      imagePullSecrets:
      - name: registry-pull-secret
      containers:
      - name: {{.Name}}
        image: {{.Registry.Address}}/cotte-internal/{{.Namespace}}-{{.Name}}:__VERSION__
        imagePullPolicy: Always
        ports:
        - containerPort: {{.Port}}
          name: {{.Name}}
        command: ["java","-jar","/opt/microservice.jar","--spring.profiles.active={{.Env}}"]
        resources:
          limits:
            cpu: 1000m
            memory: 2500Mi
          requests:
            cpu: 100m
            memory: 500Mi
        livenessProbe:
          httpGet:
            path: {{.Health}}
            port: {{.Port}}
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: {{.Health}}
            port: {{.Port}}
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
spec:
  ports:
  - port: {{.Port}}
    name: {{.Name}}
    targetPort: {{.Port}}
  selector:
    app: {{.Name}}
---
{{- $NamePrefix := print "/" .Name}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{.Name}}
spec:
  gateways:
    - istio-system/gateway
  hosts:
    - {{.GatewayHost}}
  http:
    - match:
        - uri:
            prefix: {{$NamePrefix}}
      {{- if ne .Prefix $NamePrefix}}
      rewrite:
        uri: {{.Prefix}}
      {{- end}}
      route:
        - destination:
            host: {{.Name}}
            port:
              number: {{.Port}}
