apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: logs.logcontroller.k8s.io
spec:
  group: logcontroller.k8s.io
  version: v1alpha1
  names:
    kind: Log
    plural: logs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            replicas:
              type: integer
              minimum: 1
              maximum: 10
